### ISSUE TITLE
关于静态资源的问题..

### ISSUE THREAD

**Issue by Zephylaci** [zdliuccit/vue-webpack-config#1]
找了半天，发现似乎没有相关配置...
我举一个列子，我动态从JSON中获取图片地址，再动态生成HTML结构，这个时候插进去的图片地址是解析不出来的....
解决方法我看了下，通常是使用静态目录或者当模块引用，后者太傻了不提..
静态目录..我突然发现这个组合里没有配置..于是我就傻眼了.vue-cil倒是配置了..但是我只看懂了..在Build的时候同时把static目录完整的考过去..
但是这边这个，没有Biuld感觉上是在动态编译，绝对路径又引不到，理论上来说也是拷贝个static目录就能解决的..但我却并不知道要考到哪里去...
所以来问一下？

**Comment by zdliuccit** [comment]
@Tarhyru 开发模式的文件都是走的缓存中获取的。生产环境中配置了koa-static中间件，引入的文件是走这个中间件的staticMiddleWare.js
